---

# Variables globales du projet
project_name: "DevOps Quote API"

app_name: "devops_quote_api"
app_user: "devopsapp"
app_group: "{{ app_user }}"
app_dir: "/opt/{{ app_name }}"
app_src_dir: "{{ app_dir }}/current"
app_venv_dir: "{{ app_dir }}/venv"
app_config_dir: "/etc/{{ app_name }}"
app_service_name: "{{ app_name }}"
app_bind_host: "127.0.0.1"
app_port: 5000
app_public_port: 80
app_gunicorn_workers: 2
app_message: "API de demonstration deployee avec Ansible"
app_quote_seed: "Infrastructure as code, livree proprement."

db_name: "devops_quotes"
db_user: "devops_api"
db_password: "devops_api_password"
db_host: "127.0.0.1"
db_port: 5432

nginx_site_name: "{{ app_name }}"
nginx_server_name: "_"
nginx_client_max_body_size: "10m"
