---

- name: Configure PostgreSQL database
  hosts: database
  become: true
  roles:
    - role: database

- name: Configure application runtime and API
  hosts: api
  become: true
  roles:
    - role: runtime
    - role: app

- name: Configure nginx reverse proxy
  hosts: nginx
  become: true
  roles:
    - role: webserver
