---

prerun: false
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
  provision: true
ansible:
  env:
    ANSIBLE_CONFIG: ../../ansible.cfg
    ANSIBLE_LIBRARY: ${MOLECULE_VAGRANT_MODULE_PATH}
    VAGRANT_DEFAULT_PROVIDER: virtualbox
  playbooks:
    converge: ../../playbook_install.yml
lint: |
  set -e
  export ANSIBLE_ROLES_PATH=${MOLECULE_EPHEMERAL_DIRECTORY}/roles
  export ANSIBLE_COLLECTIONS_PATH=${MOLECULE_EPHEMERAL_DIRECTORY}/collections
  ansible-lint --exclude ${MOLECULE_EPHEMERAL_DIRECTORY} -c .ansible-lint.yml
  flake8
platforms:
  - name: devops-dev-1
    box: onlyoffice/base-ubuntu2404
    memory: 2048
    cpus: 1
#    provider_options:
#      gui: true # Peut être nécessaire pour Windows (WSL)
    provider_override_args:
      - "vm.provision 'shell', inline: 'apt update'"
      - "vm.provision 'shell', inline: 'locale-gen fr_FR'"
      - "vm.provision 'shell', inline: 'locale-gen fr_FR.UTF-8'"
      - "vm.provision 'shell', inline: 'update-locale'"
provisioner:
  name: ansible
  inventory:
    links:
      hosts: ../../hosts/hosts_dev
      group_vars: ../../group_vars/
scenario:
  name: default
verifier:
  name: testinfra
  options:
    sudo: true
